# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ccc_cpp <- function(X) {
    .Call(`_matrixCorr_ccc_cpp`, X)
}

ccc_with_ci_cpp <- function(X, conf_level = 0.95) {
    .Call(`_matrixCorr_ccc_with_ci_cpp`, X, conf_level)
}

openmp_threads <- function() {
    .Call(`_matrixCorr_openmp_threads`)
}

kendall_tau_auto_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_auto_cpp`, x, y, scale)
}

kendall_tau_a_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_a_cpp`, x, y, scale)
}

kendall_tau_b_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_b_cpp`, x, y, scale)
}

kendall_matrix_cpp <- function(mat) {
    .Call(`_matrixCorr_kendall_matrix_cpp`, mat)
}

pearson_matrix_cpp <- function(X_) {
    .Call(`_matrixCorr_pearson_matrix_cpp`, X_)
}

spearman_matrix_cpp <- function(X_) {
    .Call(`_matrixCorr_spearman_matrix_cpp`, X_)
}

#' Input validator for correlation
#'
#' @param data matrix or data.frame
#' @param check_na logical; if TRUE, scan and error on any NA/NaN
#' @return numeric (double) matrix with colnames preserved when available
#'
validate_corr_input_cpp <- function(data, check_na = TRUE) {
    .Call(`_matrixCorr_validate_corr_input_cpp`, data, check_na)
}

