# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kendall_tau_auto_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_auto_cpp`, x, y, scale)
}

kendall_tau_a_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_a_cpp`, x, y, scale)
}

kendall_tau_b_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_b_cpp`, x, y, scale)
}

kendall_matrix_cpp <- function(mat) {
    .Call(`_matrixCorr_kendall_matrix_cpp`, mat)
}

